### ISSUE TITLE
Add a `setup.py` into the repository home

### ISSUE THREAD

**Issue by WardLT** [AD-SDL/adc-rdm-sdk#13]
Poetry is a nice way to list out dependencies, but it doesn't play well with other Python build systems (e.g., Anaconda).

Could we add a simple `setup.py` file to the root of the project? That would allow me to list the SDK as a dependency in `requirements.txt` files (e.g., using `git+ssh://` to install directly from GitHub) or inside the pip section of an Anaconda `environment.yml` file.

**Comment by laaraujo-dnt** [comment]
We finally got the license and published it as a python package :)

```
pip install adc-sdk
```

https://pypi.org/project/adc-sdk/
