### ISSUE TITLE
Security: Upgrade aiohttp to version 3.7.4 or later

### ISSUE THREAD

**Issue by aavarca** [AD-SDL/adc-rdm-sdk#16]
See details from alert: 
https://github.com/AD-SDL/adc-rdm-sdk/security/dependabot/requirements.txt/aiohttp/open

**Comment by laaraujo-dnt** [comment]
I marked the alert as "Risk is tolerable to this project".
The alert states that it is specifically related to maliciously crafted urls, but we are the ones defining the URLs used for this project so it should not affect us for now.
